// HTMLElements.js queries and exports all HTML elements used in the app
const clientMenu = document.getElementById(`client-menu`),
    serverMenu = document.getElementById(`server-menu`),
    systemMessageList = document.getElementById(`system-message-list`),
    dataMessageList = document.getElementById(`data-message-list`),
    dataToBeSentInput = document.getElementById(`data-to-be-sent-input`),
    dataToBeSentButton = document.getElementById(`data-to-be-sent-button`),
    continueButton = document.getElementById(`continue-button`),
    clientConnectToServerButton = document.getElementById(`client-connect-to-server-button`),
    serverListenForRequestsButton = document.getElementById(`server-listen-for-requests-button`),
    clientModeRadioButton = document.getElementById(`client-mode-radio-button`),
    serverModeRadioButton = document.getElementById(`server-mode-radio-button`),
    clientDisconnectButton = document.getElementById(`client-disconnect-button`),
    serverDisconnectButton = document.getElementById(`server-disconnect-button`),
    hostnameInput = document.getElementById(`hostname-input`),
    clientsPortNumberInput = document.getElementById(`clients-port-number-input`),
    serversPortNumberInput = document.getElementById(`servers-port-number-input`),
    secretKeyInput = document.getElementById(`secret-key-input`);

module.exports = {
    clientMenu,
    serverMenu, systemMessageList,
    dataMessageList,
    dataToBeSentInput,
    dataToBeSentButton,
    continueButton,
    clientConnectToServerButton,
    serverListenForRequestsButton,
    clientModeRadioButton,
    serverModeRadioButton,
    clientDisconnectButton,
    serverDisconnectButton,
    hostnameInput,
    clientsPortNumberInput,
    serversPortNumberInput,
    secretKeyInput,
};
